# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import robot_arm_pb2 as robot__arm__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot_arm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotArmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamLandmarks = channel.stream_unary(
                '/robotarm.RobotArm/StreamLandmarks',
                request_serializer=robot__arm__pb2.Landmark.SerializeToString,
                response_deserializer=robot__arm__pb2.StreamAck.FromString,
                _registered_method=True)


class RobotArmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamLandmarks(self, request_iterator, context):
        """Client-side streaming: Python (client) -> Unity (server)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotArmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamLandmarks': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLandmarks,
                    request_deserializer=robot__arm__pb2.Landmark.FromString,
                    response_serializer=robot__arm__pb2.StreamAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotarm.RobotArm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robotarm.RobotArm', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotArm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamLandmarks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/robotarm.RobotArm/StreamLandmarks',
            robot__arm__pb2.Landmark.SerializeToString,
            robot__arm__pb2.StreamAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
