# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import robot_arm_pb2 as robot__arm__pb2


class RobotArmStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamLandmarks = channel.stream_unary(
                '/robotarm.RobotArm/StreamLandmarks',
                request_serializer=robot__arm__pb2.Landmark.SerializeToString,
                response_deserializer=robot__arm__pb2.StreamAck.FromString,
                )


class RobotArmServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamLandmarks(self, request_iterator, context):
        """Client-side streaming: Python (client) -> Unity (server)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotArmServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamLandmarks': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLandmarks,
                    request_deserializer=robot__arm__pb2.Landmark.FromString,
                    response_serializer=robot__arm__pb2.StreamAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotarm.RobotArm', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotArm(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamLandmarks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/robotarm.RobotArm/StreamLandmarks',
            robot__arm__pb2.Landmark.SerializeToString,
            robot__arm__pb2.StreamAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
