# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_arm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frobot_arm.proto\x12\x08robotarm\"J\n\x08Landmark\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"(\n\tStreamAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2H\n\x08RobotArm\x12<\n\x0fStreamLandmarks\x12\x12.robotarm.Landmark\x1a\x13.robotarm.StreamAck(\x01\x42\x10\xaa\x02\rRobotArm.Grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_arm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\rRobotArm.Grpc'
  _LANDMARK._serialized_start=29
  _LANDMARK._serialized_end=103
  _STREAMACK._serialized_start=105
  _STREAMACK._serialized_end=145
  _ROBOTARM._serialized_start=147
  _ROBOTARM._serialized_end=219
# @@protoc_insertion_point(module_scope)
